modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "All rights reserved"

[[mods]]
modId = "bambooeverything"
version = "${version}"
displayName = "Bamboo Everything"
authors = "Gaz(Gaz492)"
description = '''
All things bamboo
'''
#logoFile = ""

[[dependencies.bambooeverything]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bambooeverything]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bambooeverything]]
modId = "architectury"
mandatory = true
versionRange = "[11.0.10,)"
ordering = "AFTER"
side = "BOTH"