modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "All rights reserved"

[[mods]]
modId = "bambooeverything"
version = "${version}"
displayName = "Bamboo Everything"
authors = "Gaz(Gaz492)"
description = '''
All things bamboo
'''
#logoFile = ""

[[dependencies.bambooeverything]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bambooeverything]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bambooeverything]]
modId = "architectury"
mandatory = true
versionRange = "[4.9.83,)"
ordering = "AFTER"
side = "BOTH"