name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    uses: ./.github/workflows/std-arch.yml
    secrets:
      nanite-token: ${{ secrets.NANITE_DEPLOY }}
      curse-token: ${{ secrets.CURSE_DEPLOY }}